user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /api/v1/user

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1
